### ISSUE TITLE
getRows dispatch redux action twice

### ISSUE THREAD

**Issue by murugaratham** [stacythen/adam-ui#6]
Need to understand the rationale for setting the filtermodel. The useEffect hook sees a change in rowsParam indirectly caused by filter params changing and useEffect triggers twice.

https://github.com/stacythen/adam-ui/blob/9da89020d6ccc063428f735dbd68676e36bd1395/packages/adam-component-datagrid/src/DataGrid.tsx#L239

**Comment by stacythen** [comment]
The line 239 has been removed in v1.0.0-alpha.4.

The following settings solved the filter resetting issues:
```
filterParams: {
  newRowsAction: 'keep',
}
```
